coreisc/urls.py
from django.conf.urls import patterns, include, url
from app.views import *
from django.conf import settings
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', index),
    url(r'^eventos/$', allpages),
    url(r"^evento/(\d+)/$", pages),
    url(r"^auspicio/$", allpages),
    url(r"^planifica/$", planifica),
    url(r"^auspicio/(\d+)/$", auspicio),
    url(r'^login/$', auth_view),
    url(r'^logout/$', logout),
 	url(r'^media/(?P<path>.*)$','django.views.static.serve',
        {'document_root':settings.MEDIA_ROOT,}),
 	#url(r'^accounts/', include('registration.urls')),sin uso por ahora
    url(r'^miembro/(?P<username>[a-zA-Z0-9_.-]+)/$', account),
    url(r'^follow/(?P<username>[a-zA-Z0-9_.-]+)/$', follow),
    url(r'^nofollow/(?P<username>[a-zA-Z0-9_.-]+)/$', nofollow),
    #url(r'^accounts/(?P<username>[a-zA-Z0-9_.-]+)/$', profile),
    url(r"^remove/event/(\d+)/$", removeEvent),
    url(r"^remove/auspicio/(\d+)/$", removePubli),
    url(r"^remove/post/(\d+)/$", removePost),
    url(r"^add/event/(\d+)/$", addEvent),
    url(r"^add/auspicio/(\d+)/$", addPubli),
    url(r'^edit_profile/', edit_user),
    url(r'^checkuser/', checkUser),
    url(r'^checktrans/', checkTrans),
    url(r'^checkemail/', checkEmail),
    url(r'^process/$', process),
    #url(r'^posting/$', posting),
    url(r'^process/create/', new_user),
    url(r'^alerta/(\d+)/$',alert),
    url(r'^notificar/(?P<username>[a-zA-Z0-9_.-]+)/$',Notificar),
    url(r'^admin/', include(admin.site.urls)),
)

app/views.py
from django.shortcuts  import render_to_response,redirect
from django.http import HttpResponseRedirect,HttpResponse
from app.models import *
from django.template import RequestContext
from django.contrib import auth
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.forms import ModelForm
from django import forms
from django.conf import settings
from PIL import Image as PImage
from os.path import join as pjoin
from datetime import datetime 

class AlertForm(ModelForm):
    class Meta:
        model = Alertas
class EventForm(ModelForm):
    class Meta:
        model = Events
class UserForm(ModelForm):
    class Meta:
        model = User
'''class PostForm(ModelForm):
    class Meta:
        model = Post
        exclude = ["event","asistente"]'''


class ThumbEditForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        exclude = [ "user","tipo","n_trans","active","fecha_trans","user2","dni","first_name","last_name","telefono","sexo"]
        avatar = forms.ImageField()

class UserProfileForm(forms.ModelForm):
    tipo = forms.TypedChoiceField(choices = TIPOS)
    sexo = forms.ChoiceField(choices= SEXO,widget=forms.RadioSelect)
    class Meta:
        model = UserProfile
        exclude = [ "user"]
        avatar = forms.ImageField()

def index(request):
    if request.user.is_authenticated():
        follow_post = Follow.objects.all().filter(user1=request.user)
        post        = Post.objects.all().order_by('-pk')
        publi       = Patrocina.objects.all().order_by('-pk')
        hotel       = Patrocina.objects.all().filter(tipo = 1)
        restaurant  = Patrocina.objects.all().filter(tipo = 2)
        movil       = Patrocina.objects.all().filter(tipo = 3)
        lugar       = Patrocina.objects.all().filter(tipo = 4)
        alert       = Alertas.objects.all().filter(usuario=request.user)
        user_all    = User.objects.all()
        
        d =  dict(post=post,
            publi=publi,
            follow_post=follow_post,
            hotel=hotel,
            movil = movil,
            restaurant=restaurant,
            lugar=lugar,
            user_all=user_all,
            alert=alert,
           
            )
        return render_to_response("index.html", d, RequestContext(request))
    else:
        form = UserProfileForm()
        form2 = UserForm()
        d =  dict(form=form,form2=form2)
        return render_to_response("registration/login.html", d, RequestContext(request))

def process(request):
    if request.method=="POST": 
        print request.POST  
        form = UserProfileForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/process/complete/')   
    else:
        form = UserProfileForm()
    d=dict(form=form)
    return render_to_response("registration/login.html", d, RequestContext(request)) 


@login_required
def pages(request, pk):
    event = Events.objects.get(pk=int(pk))
    try:
        asis = Events.objects.get(asistente=request.user,pk=pk)
    except Events.DoesNotExist:
        asis = None
    d = dict(event=event,asis=asis)
    return render_to_response("pages.html", d, RequestContext(request))


def auspicio(request, pk):
    publi = Patrocina.objects.get(pk=int(pk))
    try:
        asis = Patrocina.objects.get(recomienda=request.user,pk=pk)
    except Patrocina.DoesNotExist:
        asis = None
    d = dict(publi=publi,asis=asis)
    return render_to_response("auspicio.html", d, RequestContext(request))

def checkUser(request):
    if request.is_ajax(): 
        data = request.GET.get('b','')
        if data is not 'admin':
            try:
                very = User.objects.get(username=data)
            except User.DoesNotExist:
                very = None
            if very:
                msg = False
            else:
                msg = True
        else:
            msg=False
    else:
        msg = False
    return HttpResponse(msg)

def checkTrans(request):
    if request.is_ajax(): 
        try:
            very = UserProfile.objects.get(n_trans=request.GET.get('b',''))
        except UserProfile.DoesNotExist:
            very = None
        if very:
            msg = False
        else:
            msg = True
    else:
        msg = False
    return HttpResponse(msg)

def checkEmail(request):
    if request.is_ajax(): 
        try:
            very = User.objects.get(email=request.GET.get('b',''))
        except User.DoesNotExist:
            very = None
        if very:
            msg = False
        else:
            msg = True
    else:
        msg = False
    return HttpResponse(msg)

def new_user(request):
    UserF = UserCreationForm(request.POST or None)
    if request.method == "POST" and request.is_ajax():   
          
        '''print request.POST
        if UserF.is_valid():
            UserF.save()
            new = request.POST.copy()
            #if UserF.is_valid():
            u = User.objects.create_user(new['username'],
                                 new['email'],
                                 new['password1'])
            u.is_active = False
            u.save()
            msg="<div class='alert-box a-green'>Tu Quimera fue publicada con exito.<a href='#' class='submitBlue submitBlue-active'>Publicar</a></div>"
        else:
            msg="<div class='alert-box a-red'>Ocurrio un problema al enviar datos, verifica que esten completos.<a href='#' class='submitBlue submitBlue-active'>Publicar</a></div>"
    '''
        msg="<div class='alert-box a-green'>Tu Quimera fue publicada con exito.<a href='#' class='submitBlue submitBlue-active'>Publicar</a></div>"
        UserF.save()   
    else:
        msg = "GET petitions are not allowed for this view."
    return HttpResponse(msg)

def allpages(request):
    event = Events.objects.all()
    d =  dict(event=event)
    
    return render_to_response("allpages.html", d, RequestContext(request))
    
'''def posting(request):
    if request.method == "POST":
        post = PostForm(request.POST)
        if post.is_valid():
            usuario = User.objects.get(username=request.user)
            date = post.save(commit=False)
            date.asistente = usuario
            date.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))'''

def post(user,event,texto):
    try:
        view = Post.objects.get(asistente=user,event=event)
    except Post.DoesNotExist:
        view = None
    if not view:
        post = Post.objects.create(asistente=user,event=event,body=texto)
        post.save()

def removePost(request, pk):
    """Delete comment(s) with primary key `pk` or with pks in POST."""
    if request.user.is_staff:
        Post.objects.get(pk=pk).delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required
def addEvent(request,pk):
    if request.method == 'POST':
        try:
            asis = Events.objects.get(asistente=request.user,pk=int(pk))
        except Events.DoesNotExist:
            asis = None
        if not asis:
            new = Events.objects.get(pk=int(pk))
            new.asistente.add(request.user)
            username = User.objects.get(username=request.user)
            body = request.POST.get('body','')
            post(username,new,body)
    return HttpResponseRedirect('/evento/'+pk)

@login_required   
def removeEvent(request,pk):
    try:
        asis = Events.objects.get(asistente=request.user,pk=int(pk))
    except Events.DoesNotExist:
        asis = None
    if asis:
        asis.asistente.remove(request.user)
    try:
        post = Post.objects.get(asistente=request.user,event=asis).delete()
    except Post.DoesNotExist:
        post = None    
    return HttpResponseRedirect('/evento/'+pk)
@login_required
def addPubli(request,pk):
    try:
        asis = Patrocina.objects.get(recomienda=request.user,pk=int(pk))
    except Patrocina.DoesNotExist:
        asis = None
    if not asis:
        new = Patrocina.objects.get(pk=int(pk))
        new.recomienda.add(request.user)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

@login_required   
def removePubli(request,pk):
    try:
        asis = Patrocina.objects.get(recomienda=request.user,pk=int(pk))
    except Patrocina.DoesNotExist:
        asis = None
    if asis:
        asis.recomienda.remove(request.user)       
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))       

def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/')

def edit_user(request):
    profile = UserProfile.objects.get(user=request.user)
    if request.method=="POST":   
        print request.POST
        asis = ThumbEditForm(request.POST,request.FILES,instance=profile)
        if asis.is_valid():
            asis.save()
            imfn = pjoin(settings.MEDIA_ROOT, profile.avatar.name)
            im = PImage.open(imfn)
            im.thumbnail((240,240), PImage.ANTIALIAS)
            im.save(imfn, "JPEG")
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))  

#planifica seccion
def planifica(request):
    event = Events.objects.all().order_by('fecha').filter(asistente = request.user)
    d =  dict(event=event)
    return render_to_response("planifica.html", d, RequestContext(request))

#seccion user profile
def account(request, username):
    try:
        username = User.objects.get(username=username)
    except User.DoesNotExist:
        username = None
    post = Post.objects.all().order_by('-pk').filter(asistente=username)
    follow = Follow.objects.filter(user1=request.user,user2=username)
    count_follow = Follow.objects.all().filter(user1=username)
    count_follower = Follow.objects.all().filter(user2=username)
    Alert = AlertForm()
    d =  dict(username=username,post=post,follow=follow,count_follow=count_follow,count_follower=count_follower,Alert=Alert)
    if username is not None:

coreisc/templates/allpages.html
{% extends "index.html" %}
{% block content %}
{% load staticfiles %}
<div class="col-lg-9">
<div class="row">
	{% for event in event %}
	<div class="col-sm-5 col-md-5 col-lg-5">
		<div class="panel panel-default">
			<div class="panel-heading">
				<div class="media">
		        <div class="pull-left">
		        	<h5 class="text-danger text-center"><strong>{{ event.fecha|date:'M'}}</strong></h5>
		          	<h1>{{ event.fecha|date:'d'}}</h1>
		        </div>
		        <div class="media-body">
		          <a href="/evento/{{event.pk}}" title=""><h4 class="media-heading">{{event.title}}</h4></a>
		         <h6>{{ event.fecha|date:'h:i A'}}</h6> 
		        </div>
		      </div>
			</div>	
			<div class="panel-body">
				<span><img src="/media/{{ event.ponente.avatar }}" class="img-circle" width="40px;">Ponente: {{ event.ponente }}</span>	
			<p class=" label label-danger"><span class="glyphicon glyphicon-calendar"></span>
			{{ event.fecha }} </p>
			</div>
		</div>
	</div>
	{% empty %}
		<div class="panel panel-default">
			<a href="" title="" class="btn btn-danger">Agregar Nuevo Evento</a>
		</div>
		<div class="panel panel-default">
			No hay eventos
		</div>
	{% endfor %}
</div>
</div>
{% endblock %}				

coreisc/templates/auspicio.html
{% extends "index.html" %}
{% block content %}
{% load staticfiles %}

<div class="col-sm-9 col-md-9 col-lg-9">
	{% if publi.banner %}<div class="panel" style="background:url(/media/{{ publi.banner }});">
	{% else %}
<div class="panel">
		{% endif%}
		<p class="titulo">
			{% block title %}{{ publi.nombre }}{% endblock %}
		</p>
		</br></br></br>
		{% if publi.banner %}
		</br></br></br></br></br></br></br>
		{% endif %}
		<div class="panel-footer">
				{% if asis %}
				<a href="/remove/auspicio/{{ publi.pk }}" class="btn btn-success remove"><button type="button" class="close">&times;</button>Lo recomiendo</a>
				{% else %}
				<a href="/add/auspicio/{{ publi.pk }}" class="btn btn-danger" id="{{publi.pk}}" class="add" title="">Recomendar</a>
				{% endif %}
			<div class="pull-right">
				<div class=" label label-danger">Lugar: {{publi.direccion}}</div>
			</div>
		</div>
	</div>
  <div class="panel panel-default" id="map" style="width: 100%; height: 100%">
  
  </div>
	<div class="panel">
		<div class="panel-heading">
			Caracteristicas:
		</div>
		<p>
			{{ publi.body }}
		</p>
	</div>
</div>
{% endblock %}				

coreisc/templates/index.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="es">
    <head>
        <meta charset="utf-8">
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{% block title %}Coreisc UNPRG Plataforma{% endblock %}</title>
        <link rel="stylesheet" href="{% static "css/bootstrap.css" %}">
        <link rel="stylesheet" href="{% static "css/bootstrap-glyphicons.css" %}">
        
        <link rel="stylesheet" href="{% static "css/main.css" %}">
    </head>
    <body onload="initialize()">
    	<div id="fb-root"></div>
									<script>(function(d, s, id) {
									  var js, fjs = d.getElementsByTagName(s)[0];
									  if (d.getElementById(id)) return;
									  js = d.createElement(s); js.id = id;
									  js.src = "//connect.facebook.net/es_LA/all.js#xfbml=1&appId=239952139479434";
									  fjs.parentNode.insertBefore(js, fjs);
									}(document, 'script', 'facebook-jssdk'));</script>
    <header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
	  <div class="container">
	    <div class="navbar-header">
	      <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a href="/" class="navbar-brand">COREISC</a>
	    </div>
	    <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
	      <ul class="nav navbar-nav">
	        <li>
	          <a href="/planifica">Planifica</a>
	        </li>
	        <li>
	          <a href="/eventos">Eventos</a>
	        </li>
	        <li>
	          <a href="/components">Components</a>
	        </li>
	      </ul>
	    </nav>
	  </div>
	</header>
        <section>
        	<div class="container">
        		<div class="row">
        			<div class="col-sm-3 col-md-3 col-lg-3  SecUser">
						<div class="panel panel-default">
							<div class="panel-heading clearfix text-center">{{ user.get_full_name}} 
							</div>
							<div class="panel-body">
								<center>
								<div id="img_avatar">
									<img  src="/media/{{ user.get_profile.avatar|default:"thum/Steven_Wells.jpg"  }}" class="img-thumbnail">
								</div>
								<a data-toggle="modal" href="#picture" class="btn btn-primary btn-xs"><strong>Editar foto</strong></a>
								 <div class="modal fade" id="picture">
								    <div class="modal-dialog">
								      <div class="modal-content">
								        <div class="modal-header">
								          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
								          <h4 class="modal-title">Edit picture</h4>
								        </div>
								         <form id="img" action="/edit_miembro/" enctype="multipart/form-data" method="post">{% csrf_token %}
								        <div class="modal-body">
			                                <input type="file" name="avatar" id="id_avatar">
								        </div>
								        <div class="modal-footer">
			                                <input type="submit" value="guardar" class="btn btn-danger">
			                            </div>
								         </form>
								      </div>
								    </div>
								  </div>
								</center>
							</div>
							<div class="panel-footer">
								<div align="center">
								<a href="/miembro/{{user}}" title="" class="btn btn-primary btn-sm" rel="tooltip" data-original-title="Perfil"><span class="glyphicon glyphicon-user"></span></a>
								<a href="" title="" class="btn btn-primary btn-sm" rel="tooltip" data-original-title="Mensajes"><span class="glyphicon glyphicon-envelope"></span></a>{% if user.is_staff %}
								<a href="/admin/" title="" class="btn btn-primary btn-sm" rel="tooltip" data-original-title="Administracion"><span class="glyphicon glyphicon-cog"></span></a>{% endif%}
								<a href="/logout/" title="" class="btn btn-primary btn-sm" rel="tooltip" data-original-title="Salir"><span class="glyphicon glyphicon-off"></span></a>
								</div>
							</div>	
						</div>
						<div class="list-group">
						  <a href="#" class="list-group-item active">¿Que buscas?</a>
						  <a href="#" class="list-group-item">Hoteles <span class="badge">{{ hotel.count}}</span></a>
						  <a href="#" class="list-group-item">Restaurants <span class="badge">{{ restaurant.count}}</span></a>
						  <a href="#" class="list-group-item">Movilidades <span class="badge">{{ movil.count}}</span></a>
						  <a href="#" class="list-group-item">Lugares Turisticos<span class="badge">{{ lugar.count}}</span></a>
						</div>
        			</div>
        			{% block content %}
        			<!-- columna central-->
					<div class="col-sm-6 col-md-6 col-lg-6">
						{% for alert in alert %}
							{% if alert.visto %}
							{%else%}
							<div class="alert alert-{{alert.tipo}}"><a href="/alerta/{{alert.pk}}" class="close">&times;</a>
								<strong>{{alert.get_tipo_display}}:</strong>
								<p>{{alert.mensaje}}</p>
							</div>
							{% endif %}
						{% endfor %}
						<!--<form action="/posting/" method="post" class="form-horizontal">
							{% csrf_token %}
						<div class="panel panel-default">
							<div class="panel-heading">Publica Algo interesante</div>
							<div class="form-group">
								<div class="col-lg-12">
									<textarea id="id_body" placeholder="Escribe tu publicacion aqui." class="form-control" rows="2"  name="body"></textarea>
								</div>
							</div>
							<div class="panel-footer">
								<div>
									<input type="submit" class="btn btn-danger" value="Publicar">
								</div>
							</div>
						</div>
					</form>-->
						{% if follow_post.count = 0 %}
							<div class="panel panel-default">
								<div class="panel-heading">
									Te sugerimos seguir a:
								</div>
								<ul class="list-group">
								{%for all in user_all%}
									{% if  all.uni == user.uni and all != user  %}
										<li class="list-group-item">
											<a href="/miembro/{{all}}"><img src="/media/{{all.get_profile.avatar}}" width="32px">
											{{all.get_full_name}}</a>
											<div class="pull-right">
												<a href="/follow/{{all}}" class="btn btn-danger" title="">Seguir</a>
											</div>
										</li>
									{%endif%}
								{%endfor%}
							  </ul>
							</div>
						{% endif %}
						{% for post in post %}
						 {%for follow_post in follow_post%}
						 	{% if post.asistente = follow_post.user2  or post.asistente = user %}
						 	<div class="panel panel-default">
								<div class="panel-heading">
									{% if user.is_staff %}
									<a href="/remove/post/{{ post.pk}}" class="close">&times;</a>
									{% endif%}
									<div class="media">
								        <div class="pull-left">
								        	<a href="/miembro/{{post.asistente}}" title=""><img src="/media/{{ post.asistente.get_profile.avatar }}" width="30px"></a>
								        </div>
								        <div class="media-body">
								        	<h5><a href="/miembro/{{post.asistente}}" title="">{{ post.asistente.first_name }}</a>
								        	{% if post.event %}
								        		<small>asistira a una conferencia</small>
								        	{%else%}
								        		<small>a hecho una publicaci&oacute;n</small>
								        	{%endif%}
								        		<br>
								        		<small class="timeago " title="{{ post.time|date:'Y-m-d H:i:s'}}"></small></h5>

								        </div>
								    </div> 
								</div>
								{%if post.body%}
								<blockquote><small>{{post.body}}</small></blockquote>
								{%endif%}
								{% if post.event %}
								<div class="panel-body-img">
									<a href="/evento/{{post.event.pk}}" title=""><img src="/media/{{post.event.banner}}" alt="{{post.event.title}}"></a>
								{%endif%}
								</div>
								<div class="panel-footer">
									{% if post.event %}
									<div class="media">
								        <div class="pull-left">
								        	<h5 class="text-danger text-center"><strong>{{ post.event.fecha|date:'M'}}</strong></h5>
								          	<h1>{{ post.event.fecha|date:'d'}}</h1>
								        </div>
								        <div class="media-body">
								          <a href="/evento/{{post.event.pk}}" title=""><h4 class="media-heading">{{post.event.title}}</h4></a>
								         <h6>{{ post.event.fecha|date:'h:i A'}}</h6> 
								        </div>
							        </div>
							      	{%endif%}
									<!--<div class="fb-comments" data-href="http://example.com" data-width="530"></div>-->
								</div>	
							</div>
						 	{% endif%}
						    {% endfor %}
						{% empty%}
						<div class="panel panel-default"><div class="panel-body">no hay ninguna publicacion hoy</div></div>
						{% endfor %}
					</div>
					<div class="col-sm-3 col-md-3 col-lg-3">
						<div class="panel panel-default">
							<div class="panel-heading">
								<h5>Te sugerimos seguir a:<br>
								<small><abbr title="Filtro:{{user.get_profile.get_uni_display}}">Filtro</abbr></small></h5>
							</div>
							<ul class="list-group">
							{%for all in user_all%}
							{% for follow_post in follow_post%}
							{%if follow_post.user2 != all %}
								{% if  all.uni == user.uni and all != user  %}
									<li class="list-group-item">
										<a href="/miembro/{{all}}"><!--<img src="/media/{{all.get_profile.avatar}}" width="32px">-->
										<strong>{{all.first_name}}</strong></a>
										<div class="pull-right">
											<a href="/follow/{{all}}" class="btn btn-danger  btn-xs" title="">Seguir</a>
										</div>
									</li>
								{%endif%}
							{% endif %}
							{% endfor %}
							{%endfor%}
						  </ul>
						</div>
						{% for publi in publi %}
						<div class="panel panel-default">
						  <div class="panel-heading">
						  	<div class="media">
						  		<div class="pull-left"  rel="tooltip" data-original-title="{{ publi.recomienda.count }} recomendaron esto" data-placement="bottom">
						        	<h4 class="text-danger text-center"><strong>+{{ publi.recomienda.count }}</strong></h4>
						        </div>
						  		<div class="media-body">
						  			<h5><a href="/auspicio/{{ publi.pk }}" title="">{{ publi.nombre }}</a>
						  				<br><small><a href="" title="">{{publi.get_tipo_display}}</a></small></h5>
						  		</div>
						  	</div> 
						  </div>
						  <div class="panel-body-img" id="map-canvas">
                {%if publi.banner %}<a href="/auspicio/{{ publi.pk }}" title=""><img src="/media/{{ publi.banner }}" ></a>{% endif %}
						  </div>
						</div>
			
						{% endfor%}
					</div>
					{% endblock %}
				</div>
        	</div>
        </section>
        <footer>
	        <div class="container"><p>© Coreisc UNPRG 2014.</div>	
	    </footer>
        <script src="http://code.jquery.com/jquery-1.10.1.min.js"></script>
        <script src="{% static "js/bootstrap.js" %}"></script>
        <script src="{% static "js/bootstrap.min.js" %}"></script>
        <script src="{% static "js/jquery.timeago.js" %}"></script>
        <script src="{% static "js/jquery.timeago.es.js" %}"></script>
        <script src="{% static "js/coreisc-home.js" %}"></script>
        <script src="https://maps.googleapis.com/maps/api/js?v=3.10&key=AIzaSyBP3ZaMYVz0M19TaHkskzCYq-dncj2TxjI&sensor=true&language=es"></script>
      <script type="text/javascript">
        var map;
        function initialize() {
          var mapOptions = {
            zoom: 8,
            center: new google.maps.LatLng(-34.397, 150.644),
            mapTypeId: google.maps.MapTypeId.ROADMAP
          };
          map = new google.maps.Map(document.getElementById('map-canvas'),
                                    mapOptions);
        }
        google.maps.event.addDomListener(window, 'load', initialize);
      </script>
      <script type="text/javascript">
		    $("[rel=tooltip]").tooltip();
		    $(".timeago").timeago();
        $(".collapse").collapse();

			/*$('#img').submit(function(e){
		    	data2 = $('#img').serialize(),
					console.log(data2);
		    		$.ajax({ // create an AJAX call...
			          data: 'b='+$('#img').serialize(), // get the form data
			          type: "GET",
			          url: "/accounts/edit/user/", // the file to call
			          beforeSend: function(response){
			            $('.checkuser').html('<img src="http://www.goodleads.com/content/styles/images/preloader.gif" width="30px">');
			          },
			          success: function(response) { // on success..
			             $('.checkuser').html(response);
			          }
			      	});
		    	return false;
		    });*/

		</script>
    </body>
</html>

coreisc/templates/pagination.html
{% for entry in entries %}
    {# your code to show the entry #}
{% endfor %}

coreisc/templates/planifica.html
{% extends "index.html" %}
{% block content %}
{% load staticfiles %}
<div class="col-sm-9 col-md-9 col-lg-9">

      {% for event in event %}
      {% if event.fecha|date:'d/m/Y' = '07/04/2014' %}
        <div class="panel-group" id="accordion">
        <div class="panel panel-default">
          <div class="panel-heading">
            <h4 class="panel-title">
              <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                {{event.title}}<span class="badge">{{event.fecha|date:'h:i A'}}</span>
              </a>
            </h4>
          </div>
          <div id="collapseOne" class="panel-collapse collapse">
            <div class="panel-body">
            {{event.title}}
            </div>
          </div>
        </div>
      {% endif %}
      {% endfor %}
      {{hoy}}
      </div>
  <div class="panel">
    <!-- Default panel contents -->
    <div class="panel-heading">MARTES</div>
    <div class="panel-body">
      <p></p>
    </div>
  </div>
  <div class="panel">
    <!-- Default panel contents -->
    <div class="panel-heading">MIERCOLES</div>
    <div class="panel-body">
      <p></p>
    </div>
  </div>
  <div class="panel">
    <!-- Default panel contents -->
    <div class="panel-heading">JUEVES</div>
    <div class="panel-body">
      <p></p>
    </div>
  </div>
  
</div>
{% endblock %}        